#!/bin/bash 

INSTALL_LOC="$HOME/.local/share/cyberchef"
CONF_LOC="$HOME/.config/cyberchef"
RELEASE=$(curl -s https://api.github.com/repos/gchq/CyberChef/releases/latest | grep tag_name | cut -d '"' -f 4)
if [[ -z "$RELEASE" ]]
then
   echo "Couldn't pull latest version. :["
fi

ZIP=https://github.com/gchq/CyberChef/releases/download/$RELEASE/CyberChef_$RELEASE.zip

function setup {
    if [[ ! -d $INSTALL_LOC ]]
    then
        echo "[+] Install directory not found, creating."
        mkdir -p $INSTALL_LOC
    fi
    if [[ ! -d $CONF_LOC ]]
    then
        echo "[+] Configuration directory not found, creating."
        mkdir -p $CONF_LOC
    fi
}

function version_check {
    if [[ -f $CONF_LOC/version.txt ]]
    then
        if [[ $(cat $CONF_LOC/version.txt) != $RELEASE ]]
        then
            echo "[+] CyberChef is updating to version $RELEASE"
            update
        fi
    # Update anyways because the version file doesn't exist.
    else
        update
    fi
}

function update {
    echo "[+] New version $RELEASE located"

    echo "[+] Downloading CyberChef_$RELEASE.zip from Github"
    curl -Ls $ZIP --output $INSTALL_LOC/CyberChef_$RELEASE.zip

    echo "[+] Extracting ZIP to $INSTALL_LOC"
    unzip -q $INSTALL_LOC/CyberChef_$RELEASE.zip -d $INSTALL_LOC

    echo "[+] Cleaning up..."
    rm $INSTALL_LOC/CyberChef_$RELEASE.zip
    mv $INSTALL_LOC/CyberChef_$RELEASE.html $INSTALL_LOC/cyberchef.html

    echo $RELEASE > $CONF_LOC/version.txt
    echo "[+] Upgrade Complete."
}

function launch {
    if [[ -f $INSTALL_LOC/cyberchef.html ]]
    then
        echo "[+] Let's start cooking!™"
        xdg-open $INSTALL_LOC/cyberchef.html
    else
        echo "CyberChef isn't installed."
    fi
}

function main {
    setup
    version_check
    launch
}

main
